spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

client:
  keystore: src/main/resources/shiba-production.jks

sentry:
  environment: production

mail-gun:
  shouldCC: true