spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

mnit-esb:
  url: https://uat-svcs.dhs.mn.gov/WebServices/Alfresco/CreateDocument

feature-flag:
  submit-via-api: on
  submit-docs-via-email-for-hennepin: on
  county-anoka: off
  county-carver: off
  county-clay: off
  county-cook: off
  county-dodge: off
  county-hennepin: on
  county-morrison: off
  county-olmsted: on
  county-ottertail: off
  county-sherburne: off
  county-steele: off
  county-stlouis: off
  county-wabasha: on
  county-wadena: off
  county-waseca: off
  county-wright: on
