spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/shiba
    username: shiba
  profiles:
    include: secrets

client:
  keystore: src/main/resources/shiba-keystore.jks

mnit-esb:
  url: https://test-svcs.dhs.mn.gov/WebServices/Alfresco/CreateDocument
  jaxb-context-path: org.codeforamerica.shiba.esbwsdl

sentry:
  dsn: ${SENTRY_DSN_URL}