spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

client:
  keystore: src/main/resources/shiba-production.jks

mnit-esb:
  url: https://svcs.dhs.mn.gov/WebServices/Alfresco/CreateDocument

submit-via-email: true
mail-gun:
  shouldCC: true

send-download-alert: true
send-non-partner-county-alert: true
pagesConfig: release