derived-values:
  expeditedUtilityPayments:
    noExpeditedUtilitiesSelected:
      value: !!org.codeforamerica.shiba.output.LiteralDerivedValueConfiguration
        literal: NO_EXPEDITED_UTILITIES_SELECTED
      type: ENUMERATED_MULTI_VALUE
      condition: !!org.codeforamerica.shiba.output.conditions.AndComposableCondition
        conditions:
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: HEATING
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: COOLING
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: ELECTRICITY
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: PHONE
    heatingOrCoolingSelection:
      value: !!org.codeforamerica.shiba.output.LiteralDerivedValueConfiguration
        literal: ONE_SELECTED
      type: ENUMERATED_SINGLE_VALUE
      condition: !!org.codeforamerica.shiba.output.conditions.OrComposableCondition
        conditions:
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: HEATING
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: COOLING
    waterOrSewerSelection:
      value: !!org.codeforamerica.shiba.output.LiteralDerivedValueConfiguration
        literal: ONE_SELECTED
      type: ENUMERATED_SINGLE_VALUE
      condition: !!org.codeforamerica.shiba.output.conditions.OrComposableCondition
        conditions:
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: WATER
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: SEWER
  goingToSchool:
    ccapHasCostsForChildCare:
      value: !!org.codeforamerica.shiba.output.LiteralDerivedValueConfiguration
        literal: CCAP_HAS_COSTS_FOR_CHILD_CARE
      type: ENUMERATED_MULTI_VALUE
      condition: !!org.codeforamerica.shiba.output.conditions.OrComposableCondition
        conditions:
          - !!org.codeforamerica.shiba.output.conditions.AndComposableCondition
            conditions:
              - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
                pageName: goingToSchool
                input: goingToSchool
                value: "true"
              - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
                pageName: choosePrograms
                input: programs
                value: CHILD_CARE
          - !!org.codeforamerica.shiba.output.conditions.DerivedCondition
            pageName: ccapJob
            input: currentlyLookingForJob
            value: "true"
  mailingAddress:
    zipCode:
      type: SINGLE_VALUE
      value: !!org.codeforamerica.shiba.output.ReferenceDerivedValueConfiguration
        pageName: homeAddress
        inputName: zipCode
      condition: !!org.codeforamerica.shiba.output.conditions.DerivedCondition
        pageName: homeAddress
        input: sameMailingAddress
        value: "true"
    city:
      type: SINGLE_VALUE
      value: !!org.codeforamerica.shiba.output.ReferenceDerivedValueConfiguration
        pageName: homeAddress
        inputName: city
      condition: !!org.codeforamerica.shiba.output.conditions.DerivedCondition
        pageName: homeAddress
        input: sameMailingAddress
        value: "true"
    state:
      type: SINGLE_VALUE
      value: !!org.codeforamerica.shiba.output.ReferenceDerivedValueConfiguration
        pageName: homeAddress
        inputName: state
      condition:
        conditions: !!org.codeforamerica.shiba.output.conditions.DerivedCondition
          pageName: homeAddress
          input: sameMailingAddress
          value: "true"
    streetAddress:
      type: SINGLE_VALUE
      value: !!org.codeforamerica.shiba.output.ReferenceDerivedValueConfiguration
        pageName: homeAddress
        inputName: streetAddress
      condition:
        conditions: !!org.codeforamerica.shiba.output.conditions.DerivedCondition
          pageName: homeAddress
          input: sameMailingAddress
          value: "true"
    apartmentNumber:
      type: SINGLE_VALUE
      value: !!org.codeforamerica.shiba.output.ReferenceDerivedValueConfiguration
        pageName: homeAddress
        inputName: apartmentNumber
      condition:
        conditions: !!org.codeforamerica.shiba.output.conditions.DerivedCondition
          pageName: homeAddress
          input: sameMailingAddress
          value: "true"