derived-values:
  expeditedUtilityPayments:
    noExpeditedUtilitiesSelected:
      value:
        literal: NO_EXPEDITED_UTILITIES_SELECTED
      type: ENUMERATED_MULTI_VALUE
      condition: !!org.codeforamerica.shiba.output.AndCompositeCondition
        conditions:
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: HEATING
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: COOLING
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: ELECTRICITY
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: DOES_NOT_CONTAIN
            value: PHONE
    heatingOrCoolingSelection:
      value:
        literal: ONE_SELECTED
      type: ENUMERATED_SINGLE_VALUE
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: HEATING
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: COOLING
    waterOrSewerSelection:
      value:
        literal: ONE_SELECTED
      type: ENUMERATED_SINGLE_VALUE
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: WATER
          - pageName: expeditedUtilityPayments
            input: payForUtilities
            matcher: CONTAINS
            value: SEWER
  goingToSchool:
    ccapHasCostsForChildCare:
      value:
        literal: CCAP_HAS_COSTS_FOR_CHILD_CARE
      type: ENUMERATED_MULTI_VALUE
      condition: !!org.codeforamerica.shiba.output.AndCompositeCondition
        conditions:
          - pageName: goingToSchool
            input: goingToSchool
            value: "true"
          - pageName: choosePrograms
            input: programs
            value: CHILD_CARE
  mailingAddress:
    zipCode:
      type: SINGLE_VALUE
      value:
        type: REFERENCE
        reference:
          pageName: homeAddress
          inputName: zipCode
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: homeAddress
            input: sameMailingAddress
            value: "true"
    city:
      type: SINGLE_VALUE
      value:
        type: REFERENCE
        reference:
          pageName: homeAddress
          inputName: city
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: homeAddress
            input: sameMailingAddress
            value: "true"
    state:
      type: SINGLE_VALUE
      value:
        type: REFERENCE
        reference:
          pageName: homeAddress
          inputName: state
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: homeAddress
            input: sameMailingAddress
            value: "true"
    streetAddress:
      type: SINGLE_VALUE
      value:
        type: REFERENCE
        reference:
          pageName: homeAddress
          inputName: streetAddress
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: homeAddress
            input: sameMailingAddress
            value: "true"
    apartmentNumber:
      type: SINGLE_VALUE
      value:
        type: REFERENCE
        reference:
          pageName: homeAddress
          inputName: apartmentNumber
      condition: !!org.codeforamerica.shiba.output.OrCompositeCondition
        conditions:
          - pageName: homeAddress
            input: sameMailingAddress
            value: "true"