derived-values:
  - groupName: ccapHasCostsForChildCare
    fieldName: ccapHasCostsForChildCare
    values:
      - value: !!org.codeforamerica.shiba.output.LiteralDerivedValueConfiguration
          literal: "true"
        type: ENUMERATED_SINGLE_VALUE
        condition:
          logicalOperator: AND
          conditions:
            - pageName: goingToSchool
              input: goingToSchool
              value: "true"
            - pageName: choosePrograms
              input: programs
              value: CCAP
      - value: !!org.codeforamerica.shiba.output.LiteralDerivedValueConfiguration
          literal: "true"
        type: ENUMERATED_SINGLE_VALUE
        condition:
          logicalOperator: AND
          conditions:
            - pageName: ccapJob
              input: currentlyLookingForJob
              value: "true"
            - pageName: choosePrograms
              input: programs
              value: CCAP