expedited-eligibility:
  assets:
    pageName: liquidAssets
    inputName: liquidAssets
    defaultValue: 0
  income:
    pageName: thirtyDayIncome
    inputName: moneyMadeLast30Days
  migrantWorker:
    pageName: migrantFarmWorker
    inputName: migrantOrSeasonalFarmWorker
  housingCosts:
    pageName: expeditedExpensesAmount
    inputName: expeditedExpensesAmount
    defaultValue: 0
  utilityExpensesSelections:
    pageName: utilityPayments
    inputName: payForUtilities