pages:
  landing:
    pageTitle: landing.title
    nextPage: prepareToApply
  prepareToApply:
    pageTitle: prepare-to-apply.title
    previousPage: landing
    nextPage: languagePreferences
  languagePreferences:
    pageTitle: language-preferences.title
    headerKey: language-preferences.language-preferences
    nextPage: choosePrograms
    previousPage: prepareToApply
    inputs:
      - name: spokenLanguage
        type: SELECT
        promptMessageKey: language-preferences.what-language-do-you-prefer-to-speak
        helpMessageKey: language-preferences.the-county-will-do-their-best-to-connect-you-with-someone-who-speaks-your
        options:
          - value: ENGLISH
            messageKey: language-preferences.english
          - value: SPANISH
            messageKey: language-preferences.spanish
          - value: SOOMAALI
            messageKey: language-preferences.soomaali
          - value: VIETNAMESE
            messageKey: language-preferences.vietnamese
          - value: RUSSIAN
            messageKey: language-preferences.russian
          - value: HMOOB
            messageKey: language-preferences.hmoob
      - name: writtenLanguage
        type: SELECT
        promptMessageKey: language-preferences.what-language-do-you-prefer-to-read-or-write
        helpMessageKey: language-preferences.the-county-will-do-their-best-to-provide-documents-in-your-preferred-language
        options:
          - value: ENGLISH
            messageKey: language-preferences.english
          - value: SPANISH
            messageKey: language-preferences.spanish
          - value: SOOMAALI
            messageKey: language-preferences.soomaali
          - value: VIETNAMESE
            messageKey: language-preferences.vietnamese
          - value: RUSSIAN
            messageKey: language-preferences.russian
          - value: HMOOB
            messageKey: language-preferences.hmoob
      - name: needInterpreter
        type: RADIO
        promptMessageKey: language-preferences.do-you-need-an-interpreter
        options:
          - value: true
            messageKey: general.inputs.yes
          - value: false
            messageKey: general.inputs.no
  choosePrograms:
    pageTitle: choose-programs.title
    nextPage: howItWorks
    previousPage: languagePreferences
    headerKey: choose-programs.what-do-you-need-help-with-today
    headerHelpMessageKey: choose-programs.check-all-that-apply
    inputs:
      - name: programs
        type: CHECKBOX
        validator:
          validation: SELECT_AT_LEAST_ONE
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        options:
          - value: FOOD
            messageKey: choose-programs.food-snap
          - value: CASH
            messageKey: choose-programs.cash-programs
          - value: EMERGENCY
            messageKey: choose-programs.emergency-assistance
          - value: CHILD_CARE
            messageKey: choose-programs.child-care-assistance
  howItWorks:
    pageTitle: how-it-works.title
    previousPage: choosePrograms
    nextPage: introBasicInfo
    dataSource:
      screenName: choosePrograms
      inputs:
        - name: programs
          valueMessageKeys:
            FOOD: how-it-works.food
            CASH: how-it-works.cash
            CHILD_CARE: how-it-works.child-care
            EMERGENCY: how-it-works.emergency
  introBasicInfo:
    pageTitle: intro-basic-info.title
    previousPage: howItWorks
    nextPage: personalInfo
  personalInfo:
    pageTitle: personal-info.title
    headerKey: personal-info.tell-us-about-yourself
    previousPage: introBasicInfo
    nextPage: contactInfo
    inputs:
      - name: firstName
        type: TEXT
        promptMessageKey: personal-info.whats-your-first-name
        helpMessageKey: personal-info.legally-as-it-appears-on-your-id
        validator:
          validation: NOT_BLANK
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: lastName
        type: TEXT
        promptMessageKey: personal-info.whats-your-last-name
        helpMessageKey: personal-info.legally-as-it-appears-on-your-id
        validator:
          validation: NOT_BLANK
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: otherName
        type: TEXT
        promptMessageKey: personal-info.list-any-names-that-you-have-gone-by-in-the-past
        helpMessageKey: personal-info.include-maiden-names-or-legal-changes
      - name: dateOfBirth
        type: DATE
        validator:
          validation: DATE
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        promptMessageKey: personal-info.when-were-you-born
      - name: ssn
        type: NUMBER
        validator:
          validation: SSN
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        promptMessageKey: personal-info.whats-your-social-security-number
        helpMessageKey: personal-info.if-you-have-one-we-strongly-recommend-including-it-here-your-caseworker-will
      - name: maritalStatus
        type: RADIO
        promptMessageKey: personal-info.whats-your-marital-status
        options:
          - value: NEVER_MARRIED
            messageKey: personal-info.never-married
          - value: MARRIED_LIVING_WITH_SPOUSE
            messageKey: personal-info.married-living-with-spouse
          - value: MARRIED_NOT_LIVING_WITH_SPOUSE
            messageKey: personal-info.married-not-living-with-spouse
          - value: LEGALLY_SEPARATED
            messageKey: personal-info.legally-separated
          - value: DIVORCED
            messageKey: personal-info.divorced
          - value: WIDOWED
            messageKey: personal-info.widowed
      - name: sex
        type: RADIO
        promptMessageKey: personal-info.whats-your-sex
        helpMessageKey: personal-info.legally-as-it-appears-on-your-id-we-regret-that-this-question-is-limited
        options:
          - value: FEMALE
            messageKey: personal-info.female
          - value: MALE
            messageKey: personal-info.male
          - value: RATHER_NOT_SAY
            messageKey: personal-info.rather-not-say
      - type: RADIO
        name: livedInMnWholeLife
        promptMessageKey: personal-info.have-you-lived-in-minnesota-your-whole-life
        options:
          - value: false
            messageKey: general.inputs.no
          - value: true
            messageKey: general.inputs.yes
        followUpsValue: true
        followUps:
          - name: moveToMnDate
            type: DATE
            validator:
              validation: DATE
            validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
            promptMessageKey: personal-info.when-did-you-move-to-minnesota
          - name: moveToMnPreviousCity
            type: TEXT
            promptMessageKey: personal-info.what-city-did-you-move-from
  contactInfo:
    pageTitle: contact-info.title
    headerKey: contact-info.how-can-we-stay-in-touch-with-you
    headerHelpMessageKey: contact-info.most-of-our-communication-will-be-through-mail
    previousPage: personalInfo
    nextPage: branchToMinimalFlow
    inputs:
      - name: phoneNumber
        type: TEXT
        promptMessageKey: contact-info.whats-your-phone-number
        validator:
          validation: NOT_BLANK
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: phoneNumberAgain
        type: TEXT
        promptMessageKey: contact-info.type-your-phone-number-again
        helpMessageKey: contact-info.lets-make-sure-that-we-have-it-right
      - name: email
        type: TEXT
        promptMessageKey: contact-info.whats-your-email-address
        validator:
          validation: NOT_BLANK
          condition:
            input: phoneOrEmail
            value: EMAIL
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: phoneOrEmail
        type: CHECKBOX
        promptMessageKey: contact-info.where-can-we-send-you-a-receipt-of-your-completed-application
        helpMessageKey: contact-info.this-is-for-your-own-records
        options:
          - value: TEXT
            messageKey: contact-info.text-me
          - value: EMAIL
            messageKey: contact-info.email-me
  branchToMinimalFlow:
    pageTitle: branch-to-minimal-flow.title
    previousPage: contactInfo
    nextPage: weDoNotRecommendMinimalFlow
    dataSource:
      screenName: personalInfo
  weDoNotRecommendMinimalFlow:
    pageTitle: we-do-not-recommend-minimal-flow.title
    previousPage: branchToMinimalFlow
    nextPage: homeAddress
  homeAddress:
    headerKey: home-address.where-are-you-currently-living
    pageTitle: home-address.title
    previousPage: weDoNotRecommendMinimalFlow
    nextPage: success
    inputs:
      - name: zipCode
        type: TEXT
        promptMessageKey: home-address.what-is-the-zip-code
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        validator:
          validation: NOT_BLANK
          condition:
            input: isHomeless
            matcher: NOT_PRESENT
      - name: city
        type: TEXT
        promptMessageKey: home-address.what-is-the-city
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        validator:
          validation: NOT_BLANK
          condition:
            input: isHomeless
            matcher: NOT_PRESENT
      - name: streetAddress
        type: TEXT
        promptMessageKey: home-address.what-is-the-street-address
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        validator:
          validation: NOT_BLANK
          condition:
            input: isHomeless
            matcher: NOT_PRESENT
      - name: apartmentNumber
        type: TEXT
        promptMessageKey: home-address.apartment-number
      - name: isHomeless
        type: CHECKBOX
        options:
          - value: true
            messageKey: home-address.im-homeless-right-now
  success:
    pageTitle: success.title