parsing:
  snapExpeditedEligibility:
    pageInputs:
      assets:
        pageName: liquidAssets
        inputName: liquidAssets
        defaultValue: 0
      income:
        pageName: thirtyDayIncome
        inputName: moneyMadeLast30Days
        defaultValue: 0
      migrantWorker:
        pageName: migrantFarmWorker
        inputName: migrantOrSeasonalFarmWorker
        required: true
      housingCosts:
        pageName: homeExpensesAmount
        inputName: homeExpensesAmount
        defaultValue: 0
      utilityExpensesSelections:
        pageName: utilityPayments
        inputName: payForUtilities
        required: true
      applicantPrograms:
        pageName: choosePrograms
        inputName: programs
      householdPrograms:
        pageName: householdMemberInfo
        inputName: programs
        groupName: household
      preparingMealsTogether:
        pageName: preparingMealsTogether
        inputName: isPreparingMealsTogether
  grossMonthlyIncome:
    groupName: jobs
    pageInputs:
      lastThirtyDaysJobIncome:
        pageName: lastThirtyDaysJobIncome
        inputName: lastThirtyDaysJobIncome
        groupName: jobs
  homeAddress:
    pageInputs:
      county:
        pageName: homeAddress
        inputName: enrichedCounty
        defaultValue: Other
      isHomeless:
        pageName: homeAddress
        inputName: isHomeless
      sameMailingAddress:
        pageName: homeAddress
        inputName: sameMailingAddress
  mailingAddress:
    pageInputs:
      county:
        pageName: mailingAddress
        inputName: enrichedCounty
        defaultValue: Other
  identifyCounty:
    pageInputs:
      county:
        pageName: identifyCounty
        inputName: county
        defaultValue: Other