screens:
  personal-info:
    inputs:
    - name: first-name
      type: TEXT
      promptMessageKey: personal-info.whats-your-first-name
      helpMessageKey: personal-info.legally-as-it-appears-on-your-id
      validationExpression: "!#this[0].isBlank()"
      validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
    - name: last-name
      type: TEXT
      promptMessageKey: personal-info.whats-your-last-name
      helpMessageKey: personal-info.legally-as-it-appears-on-your-id
      validationExpression: "!#this[0].isBlank()"
      validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
    - name: other-name
      type: TEXT
      promptMessageKey: personal-info.list-any-names-that-you-have-gone-by-in-the-past
      helpMessageKey: personal-info.include-maiden-names-or-legal-changes
    - name: date-of-birth
      type: DATE
      promptMessageKey: personal-info.when-were-you-born