screens:
  landing:
    nextPage: prepare-to-apply
    previousPage: landing
  prepare-to-apply:
    previousPage: landing
    nextPage: language-preferences
  language-preferences:
    pageTitle: language-preferences.language-preferences
    headerKey: language-preferences.language-preferences
    nextPage: choose-programs
    previousPage: prepare-to-apply
    inputs:
      - name: spoken-language
        type: SELECT
        promptMessageKey: language-preferences.what-language-do-you-prefer-to-speak
        helpMessageKey: language-preferences.the-county-will-do-their-best-to-connect-you-with-someone-who-speaks-your
        options:
          - value: ENGLISH
            messageKey: language-preferences.english
          - value: SPANISH
            messageKey: language-preferences.spanish
          - value: SOOMAALI
            messageKey: language-preferences.soomaali
          - value: VIETNAMESE
            messageKey: language-preferences.vietnamese
          - value: RUSSIAN
            messageKey: language-preferences.russian
          - value: HMOOB
            messageKey: language-preferences.hmoob
      - name: written-language
        type: SELECT
        promptMessageKey: language-preferences.what-language-do-you-prefer-to-read-or-write
        helpMessageKey: language-preferences.the-county-will-do-their-best-to-provide-documents-in-your-preferred-language
        options:
          - value: ENGLISH
            messageKey: language-preferences.english
          - value: SPANISH
            messageKey: language-preferences.spanish
          - value: SOOMAALI
            messageKey: language-preferences.soomaali
          - value: VIETNAMESE
            messageKey: language-preferences.vietnamese
          - value: RUSSIAN
            messageKey: language-preferences.russian
          - value: HMOOB
            messageKey: language-preferences.hmoob
      - name: need-interpreter
        type: RADIO
        promptMessageKey: language-preferences.do-you-need-an-interpreter
        options:
          - value: true
            messageKey: general.inputs.yes
          - value: false
            messageKey: general.inputs.no
  choose-programs:
    pageTitle: choose-programs.choose-programs
    nextPage: how-it-works
    previousPage: language-preferences
    headerKey: choose-programs.what-do-you-need-help-with-today
    headerHelpMessageKey: choose-programs.check-all-that-apply
    inputs:
      - name: programs
        type: CHECKBOX
        validator:
          validation: SELECT_AT_LEAST_ONE
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        options:
          - value: FOOD
            messageKey: choose-programs.food-snap
          - value: CASH
            messageKey: choose-programs.cash-programs
          - value: EMERGENCY
            messageKey: choose-programs.emergency-assistance
          - value: CHILD_CARE
            messageKey: choose-programs.child-care-assistance
  how-it-works:
    path: /how-it-works
    previousPage: choose-programs
    nextPage: intro-basic-info
  intro-basic-info:
    previousPage: how-it-works
    nextPage: personal-info
  personal-info:
    pageTitle: personal-info.title
    headerKey: intro-basic-info.getting-to-know-you
    previousPage: intro-basic-info
    nextPage: contact-info
    inputs:
      - name: first-name
        type: TEXT
        promptMessageKey: personal-info.whats-your-first-name
        helpMessageKey: personal-info.legally-as-it-appears-on-your-id
        validator:
          validation: NOT_BLANK
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: last-name
        type: TEXT
        promptMessageKey: personal-info.whats-your-last-name
        helpMessageKey: personal-info.legally-as-it-appears-on-your-id
        validator:
          validation: NOT_BLANK
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: other-name
        type: TEXT
        promptMessageKey: personal-info.list-any-names-that-you-have-gone-by-in-the-past
        helpMessageKey: personal-info.include-maiden-names-or-legal-changes
      - name: date-of-birth
        type: DATE
        validator:
          validation: DATE
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        promptMessageKey: personal-info.when-were-you-born
      - name: ssn
        type: NUMBER
        validator:
          validation: SSN
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
        promptMessageKey: personal-info.whats-your-social-security-number
        helpMessageKey: personal-info.if-you-have-one-we-strongly-recommend-including-it-here-your-caseworker-will
      - name: marital-status
        type: RADIO
        promptMessageKey: personal-info.whats-your-marital-status
        options:
          - value: NEVER_MARRIED
            messageKey: personal-info.never-married
          - value: MARRIED_LIVING_WITH_SPOUSE
            messageKey: personal-info.married-living-with-spouse
          - value: MARRIED_NOT_LIVING_WITH_SPOUSE
            messageKey: personal-info.married-not-living-with-spouse
          - value: LEGALLY_SEPARATED
            messageKey: personal-info.legally-separated
          - value: DIVORCED
            messageKey: personal-info.divorced
          - value: WIDOWED
            messageKey: personal-info.widowed
      - name: sex
        type: RADIO
        promptMessageKey: personal-info.whats-your-sex
        helpMessageKey: personal-info.legally-as-it-appears-on-your-id-we-regret-that-this-question-is-limited
        options:
          - value: FEMALE
            messageKey: personal-info.female
          - value: MALE
            messageKey: personal-info.male
          - value: RATHER_NOT_SAY
            messageKey: personal-info.rather-not-say
      - type: RADIO
        name: lived-in-mn-whole-life
        promptMessageKey: personal-info.have-you-lived-in-minnesota-your-whole-life
        options:
          - value: false
            messageKey: general.inputs.no
          - value: true
            messageKey: general.inputs.yes
        followUpsValue: true
        followUps:
          - name: move-to-mn-date
            type: DATE
            validator:
              validation: DATE
            validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
            promptMessageKey: personal-info.when-did-you-move-to-minnesota
          - name: move-to-mn-previous-city
            type: TEXT
            promptMessageKey: personal-info.what-city-did-you-move-from
  contact-info:
    pageTitle: contact-info.title
    headerKey: contact-info.how-can-we-stay-in-touch-with-you
    headerHelpMessageKey: contact-info.most-of-our-communication-will-be-through-mail
    previousPage: personal-info
    nextPage: success
    inputs:
      - name: phone-number
        type: TEXT
        promptMessageKey: contact-info.whats-your-phone-number
        validator:
          validation: NOT_BLANK
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: phone-number-again
        type: TEXT
        promptMessageKey: contact-info.type-your-phone-number-again
        helpMessageKey: contact-info.lets-make-sure-that-we-have-it-right
      - name: email
        type: TEXT
        promptMessageKey: contact-info.whats-your-email-address
        validator:
          validation: NOT_BLANK
          condition:
            input: phone-or-email
            value: EMAIL
        validationErrorMessageKey: general.validation.make-sure-you-answer-this-question
      - name: phone-or-email
        type: CHECKBOX
        promptMessageKey: contact-info.where-can-we-send-you-a-receipt-of-your-completed-application
        helpMessageKey: contact-info.this-is-for-your-own-records
        options:
          - value: TEXT
            messageKey: contact-info.text-me
          - value: EMAIL
            messageKey: contact-info.email-me
  success:
    previousPage: personal-info