screens:
  - name: prepare-to-apply
    template: some-template.html
  - name: language-preferences
    fields:
      - name: writtenLanguage
        type: text
        required: true
      - name: needInterpreter
        type: radio
        options:
          - name: yes
          - name: no
    nextScreen: personal-info
  - name: personal-info
    fields:
      - name: firstName
        type: text
        required: true
        pdfFieldName: APPLICANT_FIRST_NAME
      - name: lastName
        type: text
        required: true
        pdfFieldName: APPLICANT_LAST_NAME