name: Deploy to MNIT Dev

on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy to Dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.2
      env:
        webhook_url: ${{ secrets.MNIT_DEV_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.MNIT_DEV_WEBHOOK_SECRET }}
  deploystable:
    name: deploy stable
    runs-on: ubuntu-latest
    steps:
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        # URL to your OpenShift cluster.
        # Refer to Step 2.
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_NON_PROD }}

        # Authentication Token. Can use username and password instead.
        # Refer to Step 3.
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_NON_PROD }}

        # Disables SSL cert checking. Use this if you don't have the certificate authority data.
        #insecure_skip_tls_verify: true
        # This method is more secure, if the certificate from Step 4 is available.
        #certificate_authority_data: ${{ secrets.CA_DATA }}

        # Optional - this sets your Kubernetes context's current namespace after logging in.
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE_NON_PROD }}
    - name: start build
      run: |
        oc start-build mn-benefits-stable
    
    
