name: Deploy to MNIT Dev

on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy to Dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.2
      env:
        webhook_url: ${{ secrets.MNIT_DEV_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.MNIT_DEV_WEBHOOK_SECRET }}
  deploystable:
    name: deploy stable
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Latest Release
      id: fetch-latest-release
      uses: thebritican/fetch-latest-release@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_NON_PROD }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_NON_PROD }}
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE_NON_PROD }}
    - name: start build
      run: |
        oc patch bc mn-benefits-release -p '{"spec":{"source":{"git":{"ref":"${{ steps.fetch-latest-release.outputs.tag_name }}"}}}}'
        oc start-build mn-benefits-release --follow
    
    
