name: Deploy to MNIT Dev

on:
  workflow_run:
    workflows: ["Run tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy to Dev
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.2
      env:
        webhook_url: ${{ secrets.MNIT_DEV_WEBHOOK_URL }}
        webhook_secret: ${{ secrets.MNIT_DEV_WEBHOOK_SECRET }}
