name: Deploy to demo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to be released'
        required: true
        default: staging

jobs:
  draft-release:
    name: Draft a new release
    runs-on: ubuntu-latest
    steps:
      - name: Create tag name
        id: create-tagname
        run: echo "::set-output name=TAG_NAME::$(date +'%Y-%m-%d-%H%M')"
      - name: Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.create-tagname.outputs.TAG_NAME }}
          release_name: release-${{ steps.create-tagname.outputs.TAG_NAME }}
          commitish: ${{ github.event.inputs.branch }}
          body: |
            Fill in details about this release
          draft: true
          prerelease: true
  deploy:
    name: Deploy to Aptible demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - run: git fetch --prune --unshallow
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.3
        with:
          key: ${{ secrets.APTIBLE_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.APTIBLE_KNOWN_HOSTS }}
      - name: Generate Sentry release name from sha
        id: generate-release
        run: echo "::set-output name=RELEASE::$(git rev-parse HEAD)"
      - name: Push to Aptible remote branch
        run: git push -f git@beta.aptible.com:mn-shiba-prod/demo.git "${{ github.event.ref }}:${{ github.event.ref }}"
      - name: Install Aptible CLI and deploy to Aptible
        run: |
          wget -O aptible-package https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/206/pkg/aptible-toolbelt_0.16.5%2B20200508143656~ubuntu.16.04-1_amd64.deb
          sudo dpkg -i aptible-package
          aptible login --email=${{ secrets.APTIBLE_USERNAME }} --password=${{ secrets.APTIBLE_PASSWORD}}
          aptible deploy --app demo --git-commitish ${{ github.event.ref }} SPRING_PROFILES_ACTIVE=demo \
          'MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}' \
          'SMARTY_STREET_AUTH_ID=${{ secrets.SMARTY_STREET_AUTH_ID }}' \
          'SMARTY_STREET_AUTH_TOKEN=${{ secrets.SMARTY_STREET_AUTH_TOKEN }}' \
          'CLIENT_KEYSTORE-PASSWORD=${{ secrets.CLIENT_KEYSTORE_PASSWORD}}' \
          'MNIT-ESB_USERNAME=${{ secrets.MNIT_USERNAME }}' \
          'MNIT-ESB_PASSWORD=${{ secrets.MNIT_PASSWORD }}' \
          'SHIBA_USERNAME=${{ secrets.SHIBA_USERNAME }}' \
          'SHIBA_PASSWORD=${{ secrets.SHIBA_PASSWORD }}' \
          'ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY_DEMO }}' \
          'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' \
          'SENTRY_ENVIRONMENT=demo' \
          'SENTRY_RELEASE=${{ steps.generate-release.outputs.RELEASE }}' \
          'MIXPANEL_API-KEY=${{ secrets.MIXPANEL_API_KEY_STAGING }}'
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: shiba
        with:
          environment: demo
      - name: Announce on Slack
        if: ${{ always() }}
        uses: innocarpe/actions-slack@v1.1
        with:
          status: ${{ jobs.deploy.status }}
          success_text: 'Deploy to Aptible demo succeeded :smile:'
          failure_text: 'Deploy to Aptible demo failed :frowning:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
