name: Draft a new release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to draft-release'
        required: true
        default: staging

jobs:
  merge-to-staging:
    name: Merge to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nightly Merge
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'staging'
          development_branch: 'master'
          allow_ff: true
          ff_only:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  draft-release:
    name: Draft a new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: '0'
      - name: Create tag name
        id: create-tagname
        run: echo "::set-output name=TAG_NAME::$(date +'%Y-%m-%d-%H%M')"
      - name: Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.create-tagname.outputs.TAG_NAME }}
          release_name: release-${{ steps.create-tagname.outputs.TAG_NAME }}
          body: |
            Fill in details about this release
          draft: true
          prerelease: true
