# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew clean test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Aptible
      uses: aptible/aptible-deploy-action@v1.1
      with:
        # Aptible username
        username: ${{ secrets.APTIBLE_USERNAME }}
        # Aptible password
        password: ${{ secrets.APTIBLE_PASSWORD }}
        # Aptible environment
        environment: ${{ secrets.APTIBLE_ENVIRONMENT }}
        # App handle
        app: ${{ secrets.APTIBLE_APP }}
        # Docker image
        docker_img: openjdk:14.0
