# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew clean test
  publish:
    name: Publish Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: codeforamerica/shiba/shiba-image
          tag_with_ref: true 
  deploy:
    name: Deploy to Aptible staging
    runs-on: ubuntu-latest
    needs: [test, publish]
    steps:
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v1.1
        with:
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          environment: ${{ secrets.APTIBLE_ENVIRONMENT }}
          app: ${{ secrets.APTIBLE_APP }}
          docker_img: docker.pkg.github.com/codeforamerica/shiba/shiba-image:latest
