# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run tests and deploy to staging

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew clean test
  deploy:
    name: Deploy to Aptible staging
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.3
        with:
          key: ${{ secrets.APTIBLE_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.APTIBLE_KNOWN_HOSTS }}
      - name: Generate Aptible branch name
        run: |
          export BRANCH="deploy-$(date "+%s")"
          echo "::set-env name=BRANCH::$BRANCH"
      - name: Push to Aptible remote branch
        run: git push -f ${{ secrets.APTIBLE_REPO }}:$BRANCH
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v1.1
        run: |
          aptible login email=${{ secrets.APTIBLE_USERNAME }} password=${{ secrets.APTIBLE_PASSWORD}}
          aptible deploy --app shiba-staging --git-commitish $BRANCH CLIENT_KEYSTORE-PASSWORD=${{ secrets.CLIENT_KEYSTORE_PASSWORD }}
      - name: Announce on Slack
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          success_text: 'Deploy to Aptible staging succeeded :smile:'
          failure_text: 'Deploy to Aptible staging failed :frowning:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
