
name: Merge test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Test/Deploy to Staging'
        required: true
        default: master

jobs:
  merge:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge master -> staging
        uses: robotology/gh-action-nightly-merge@v1.3.2
        with:
          stable_branch: 'staging'
          development_branch: ${{ github.events.inputs.branch || github.events.inputs.branch.default }}
          allow_ff: true
          ff_only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}