name: Test branch detection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to be released'
        required: true
        default: staging

jobs:
  determine-branch:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.branch-output.branch-name }}
    steps:
      - id: branch-output
        run: |
          if [[ "${{ github.event.inputs.branch }}" == "" ]]
          then
            echo "::set-output name=branch-name::staging"
          else
            echo "::set-output name=branch-name::${{ github.event.inputs.branch }}"
          fi
  show-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.determine-branch.outputs.branch-name }}