name: Test branch detection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to be released'
        required: true
        default: staging

jobs:
#  skipped-action:
#    runs-on: ubuntu-latest
#    if: github.event.inputs.branch != 'staging'
#    steps:
#      - run: echo ${{ github.event.inputs.branch }}
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: shiba
          POSTGRES_PASSWORD: shiba
          POSTGRES_DB: shiba-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Set up JDK
        if: github.event.inputs.branch != 'staging'
        uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Grant execute permission for gradlew
        if: github.event.inputs.branch != 'staging'
        run: chmod +x gradlew
      - name: Test with Gradle
        run: |
          if [[ "${{ github.event.inputs.branch }}" == "staging" ]]; then
            exit 0
          else
            ./gradlew clean testAll
          fi
      - name: Announce test failure on slack
        if: ${{ failure() }}
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          failure_text: 'Tests failed in CI! :disappointed:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  show-branch:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.branch }}